services:
  db:
    image: mysql:8.3
    container_name: voleapp_dev_db
    ports:
      - "3306:3306"
    env_file:
      - ./src/Web.Api/.env.dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data_dev:/var/lib/mysql
    networks:
      - voleapp-network
        
  seq:
    image: datalust/seq:2024.3
    container_name: voleapp_dev_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8082:80"
      - "5341:5341"
    volumes:
      - seq_data_dev:/data
    networks:
      - voleapp-network
  
networks:
  voleapp-network:
    driver: bridge

volumes:
  db_data_dev:
  seq_data_dev:
