services:
  db:
    image: mysql:8.3
    container_name: voleapp_staging_db
    ports:
      - "3307:3306"
    env_file:
      - ./src/Web.Api/.env.staging
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "staging", "-pstaging-secret"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
    volumes:
      - db_data_staging:/var/lib/mysql
    networks:
      - voleapp-network-staging
  
  
  seq:
    image: datalust/seq:2024.3
    container_name: voleapp_staging_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8083:80"
      - "5342:5341"
    volumes:
      - seq_data_staging:/data
    networks:
      - voleapp-network-staging
  
  
  api:
    container_name: voleapp_staging_api
    build:
      context: .
      dockerfile: ./src/Web.Api/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started
    env_file:
      - ./src/Web.Api/.env.staging
    networks:
      - voleapp-network-staging

networks:
  voleapp-network-staging:
    driver: bridge

volumes:
  db_data_staging:
  seq_data_staging:
